[package]
name = "constants"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", features = [
  "bevy_ui",
  "bevy_text",
  "bevy_winit",
  "bevy_pbr",
  "webgpu",
  "exr",
  "dds",
] }
bevy_common_assets = { version = "0.13", features = ["json"] }
