[package]
name = "point-cloud-render-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.12", features = ["exr", "dds"] }
las = { version = "0.9", features = ["laz-parallel"] }
serde_json = "1.0"
