[package]
name = "point-cloud-pre-processing"
version = "0.1.0"
edition = "2024"

[dependencies]
las = { version = "0.9", features = ["laz-parallel"] }
image = "0.24"
serde_json = "1.0"
exr = "1.7"
ddsfile = "0.5"
half = "2.3"
